### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by diplopito** [tporadowski/rejson#1]
Hi Tomasz,

I would like to try reJson, but the links in readme.md are broken. Would this version work with Redis 5?

Thanks and congratulations for the great work!

**Comment by tporadowski** [comment]
Hi @diplopito,
This repository is an outdated fork of [RedisJSON](https://github.com/RedisJSON/RedisJSON) from the times when my [Redis for Windows fork](https://github.com/tporadowski/redis) was at version 4.0.14 and I needed a real-life Redis module to test module support changes introduced there. I haven't changed the "Readme" at all, but you're of course right - they're broken now.
As for working with Redis 5 - I don't think it will, I vaguely remember some changes in modules API between v4 and v5. Recently I've been asked about it in [this StackOverflow thread](https://stackoverflow.com/a/61745484/613118) and when I looked at RedisJSON (formerly "ReJSON") it turned out to be a completely rewritten implementation done in Rust. My guess is therefore that it should probably work in Redis for Windows (5.x) with some slight changes. It's on my TODO list to try it out ;) - and then perhaps I will update this repository and provide compiled versions as well.

**Comment by diplopito** [comment]
I certainly hope that your guess will be right. Looking forward to your solution!

**Comment by diplopito** [comment]
BTW, do you know if RedisLabs has any plans of integrating RedisJSON in core? That would be so useful.

**Comment by tporadowski** [comment]
I highly doubt it. Firstly, because Redis is format-agnostic, so you can store any data in any format and having JSON as pluggable module is perfectly fine. Secondly, as I mentioned - it is now written in Rust (was in C) and Redis is written in C.

**Comment by diplopito** [comment]
Ok, so fingers crossed with your solution then :-)
